***************************************************************************

IPython post-mortem report

IPython version: 0.10.2 

Platform info  : os.name -> posix, sys.platform -> linux2

***************************************************************************

Current user configuration structure:

{'Version': 0,
 '__allownew': True,
 'alias': [],
 'args': [],
 'autocall': 2,
 'autoedit_syntax': 0,
 'autoexec': [],
 'autoindent': 0,
 'automagic': 1,
 'banner': 0,
 'c': '',
 'cache_size': 1000,
 'classic': 0,
 'color_info': 0,
 'colors': 'LightBG',
 'confirm_exit': 1,
 'debug': 0,
 'deep_reload': 0,
 'editor': '0',
 'execfile': [],
 'execute': [],
 'gthread': 0,
 'help': 0,
 'import_all': [],
 'import_mod': [],
 'import_some': [[]],
 'include': [],
 'interact': 0,
 'ipythondir': '/home/cdaley/.casa/ipython',
 'log': 0,
 'logfile': 'ipython-20170626-164716.log',
 'logplay': '',
 'magic_docstrings': 0,
 'messages': 0,
 'multi_line_specials': 1,
 'nosep': 0,
 'object_info_string_level': 0,
 'opts': Struct({'__allownew': True,
 'autocall': 2,
 'banner': 0,
 'colors': 'LightBG',
 'ipythondir': '/home/cdaley/.casa/ipython',
 'logfile': 'ipython-20170626-164716.log',
 'messages': 0,
 'prompt_in1': 'CASA <\\#>: ',
 'upgrade': 1}),
 'pdb': 0,
 'pprint': 0,
 'profile': '',
 'prompt_in1': 'CASA <\\#>: ',
 'prompt_in2': '   .\\D.: ',
 'prompt_out': 'Out[\\#]: ',
 'prompts_pad_left': 1,
 'pydb': 0,
 'pylab': 0,
 'pylab_import_all': 1,
 'q4thread': 0,
 'qthread': 0,
 'quick': 0,
 'quiet': 0,
 'rcfile': 'ipythonrc',
 'readline': 1,
 'readline_merge_completions': 1,
 'readline_omit__names': 0,
 'readline_parse_and_bind': [],
 'readline_remove_delims': '',
 'screen_length': 0,
 'separate_in': '\n',
 'separate_out': '\n',
 'separate_out2': '',
 'system_header': 'IPython system call: ',
 'system_verbose': 0,
 'term_title': 1,
 'tk': 0,
 'upgrade': 1,
 'wildcards_case_sensitive': 1,
 'wthread': 0,
 'wxversion': '0',
 'xmode': 'Context'}

***************************************************************************

Crash traceback:

---------------------------------------------------------------------------
NameError    Python 2.7.5: /soft/casa-release-4.7.2-el7/lib/casa/bin/python
                                                   Mon Jun 26 12:47:16 2017
A problem occured executing Python code.  Here is the sequence of function
calls leading up to the error, with the most recent (innermost) call last.

/soft/casa-release-4.7.2-el7/lib/python2.7/casapy.py in <module>()
   1461             try:
   1462                 ipshell = IPython.Shell.IPShell( argv=['-prompt_in1','CASA <\#>: ','-autocall','2','-colors',__ipython_colors, '-nomessages', '-nobanner','-ipythondir',casa['dirs']['rc']+'/ipython'], user_ns=globals() )
   1463             except: 
   1464                 print "ERROR: falied to create an instance of IPython.Shell.IPShell"
   1465     else:
   1466         if(thelogfile != 'null') :
   1467             try:
   1468                 ipshell = IPython.Shell.IPShell( argv=['-prompt_in1','CASA <\#>: ','-autocall','2','-colors',__ipython_colors, '-nomessages', '-nobanner','-logfile',ipythonlog,'-upgrade','-ipythondir',casa['dirs']['rc']+'/ipython'], user_ns=globals() )
   1469             except: 
   1470                 print "ERROR: falied to create an instance of IPython.Shell.IPShell"
   1471         else :
   1472             try:
   1473                 ipshell = IPython.Shell.IPShell( argv=['-prompt_in1','CASA <\#>: ','-autocall','2','-colors',__ipython_colors, '-nomessages', '-nobanner','-upgrade','-ipythondir',casa['dirs']['rc']+'/ipython'], user_ns=globals() )
   1474             except: 
   1475                 print "ERROR: falied to create an instance of IPython.Shell.IPShell"
-> 1476     ipshell.IP.runlines('execfile("'+fullpath+'")')
        global ipshell.IP.runlines = undefined
        global fullpath = '/soft/casa-release-4.7.2-el7/lib/python2.7/assignmentFilter.py'
   1477 
   1478 #ipshell = IPython.Shell.IPShell( argv=['-prompt_in1','CASA <\#>: ','-autocall','2','-colors',__ipython_colors,'-logfile',ipythonlog,'-ipythondir',casa['dirs']['rc']+'/ipython'], user_ns=globals() )
   1479 
   1480 casalog.setlogfile(thelogfile)
   1481 
   1482 try:
   1483     casalog.post('---')
   1484 except:
   1485     print "Error: the logfile is not writable"
   1486     sys.exit(1)
   1487 
   1488 
   1489 casalog.showconsole(showconsole)
   1490 casalog.version()
   1491 

NameError: name 'ipshell' is not defined

***************************************************************************

History of session input:

*** Last line of input (may not be in above history):
